pgwatch2/sql/datastore_setup/metric_definitions.sql

Incorrect syntax in sql queries for metrics buffercache_by_db/buffercache_by_type

---

grafana_dashboards/v4/global-db-overview/dashboard.json
grafana_dashboards/v4/global-db-overview/title.txt
grafana_dashboards/v4/system-stats/dashboard.json
grafana_dashboards/v4/system-stats/title.txt

Two new dashboards to Grafana v4.

Added system-stats and global-db-overview dashboards to Grafana v4

---

pgwatch2/get_dependencies.sh
pgwatch2/pgwatch2.go
pgwatch2/startup-scripts/pgwatch2.service

simple modification to made communication between pgwatch2 daemon
and SystemD

Add SystemD service file, and make pgwatch2.go managed by Systemd

---

pgwatch2/startup-scripts/pgwatch2.service
webpy/startup-scripts/pgwatch2-webui.service

Add SystemD service file for Python Web UI
Change SystemD service file for pgwatch2, to remove watchdog setting

Add SystemD for WebUI

---

README.md
openshift_k8s/chart-values.yml
openshift_k8s/helm-chart/.helmignore
openshift_k8s/helm-chart/Chart.yaml
openshift_k8s/helm-chart/templates/NOTES.txt
openshift_k8s/helm-chart/templates/_helpers.tpl
openshift_k8s/helm-chart/templates/config-pvc.yaml
openshift_k8s/helm-chart/templates/database-pvc.yaml
openshift_k8s/helm-chart/templates/deployment.yaml
openshift_k8s/helm-chart/templates/exporter-ingress.yaml
openshift_k8s/helm-chart/templates/exporter-service.yaml
openshift_k8s/helm-chart/templates/grafana-ingress.yaml
openshift_k8s/helm-chart/templates/grafana-secrets.yaml
openshift_k8s/helm-chart/templates/grafana-service.yaml
openshift_k8s/helm-chart/templates/serviceaccount.yaml
openshift_k8s/helm-chart/templates/tests/test-connection.yaml
openshift_k8s/helm-chart/templates/web-ingress.yaml
openshift_k8s/helm-chart/templates/web-secrets.yaml
openshift_k8s/helm-chart/templates/web-service.yaml
openshift_k8s/helm-chart/values.yaml

We are currently deploying pgwatch2 (with Prometheus as datastore) to our Kubernetes cluster using a Helm chart as deployment tool.
Therefore, we created a proper Helm chart, which we want to contribute to this project.
Closes #133 #165 
Greetings from [Salzburg Research](https://www.salzburgresearch.at/)

Helm Chart

---

pgwatch2/pgwatch2.go

substitude env variable in file base config

---

docs/Makefile
docs/README.rst
docs/advanced_features.rst
docs/components.rst
docs/conf.py
docs/custom_installation.rst
docs/dashboarding_alerting.rst
docs/docker_installation.rst
docs/features.rst
docs/index.rst
docs/installation_options.rst
docs/kubernetes.rst
docs/long_term_installations.rst
docs/metric_definitions.rst
docs/monitoring_preparations.rst
docs/preparing_databases.rst
docs/project_background.rst
docs/security.rst
docs/sizing_recommendations.rst
docs/technical_details.rst
docs/upgrading.rst
docs/web_ui.rst
pgwatch2/config/instances.yaml
pgwatch2/metrics/wal/metric_attrs.yaml

A new "docs" folder with .rst files

Prepare moving documentation to Readthedocs

---

pgwatch2/pgwatch2.go

Show type name instead of value

---

pgwatch2/pgwatch2.go

Fix for: https://github.com/cybertec-postgresql/pgwatch2/issues/328

Do not connect to config DB in adhoc mode

---

pgwatch2/pgwatch2.go

Reconnect to graphite

---

pgwatch2/metrics/wal_receiver/10/metric_standby.sql
pgwatch2/metrics/wal_receiver/9.2/metric_standby.sql

Missed typecast

---

grafana_dashboards/postgres/v6/alert-template/dashboard.json

Missed ORDER BY in alert-template dashboard

---

pgwatch2/metrics/index_stats/10/metric.sql
pgwatch2/metrics/index_stats/9.0/metric.sql
pgwatch2/metrics/index_stats/9.1/metric.sql
pgwatch2/metrics/table_stats/10/metric.sql
pgwatch2/metrics/table_stats/9.0/metric_master.sql
pgwatch2/metrics/table_stats/9.0/metric_standby.sql
pgwatch2/metrics/table_stats/9.1/metric_master.sql
pgwatch2/metrics/table_stats/9.1/metric_standby.sql
pgwatch2/metrics/table_stats/9.2/metric.sql
pgwatch2/sql/config_store/metric_definitions.sql

Metrics: also skip tables just waiting for AccessExclusiveLock

---

openshift_k8s/helm-chart-k8s-pg-storage/templates/deployment.yaml

Hello,
To retreive system metrics from aiven (where plpython can't be used), i need to run an extra container.
Thanks.
ps : there are 2 typos errors in emptyDir section.

feat: give possibility to add an extra container

---

.github/workflows/codeql-analysis.yml
.github/workflows/release.yml
.gitignore
.goreleaser.yml
.vscode/tasks.json

[!] add `release` GitHub Action

---

.github/workflows/codeql-analysis.yml
.github/workflows/release.yml

[+] bump `actions/setup-go` to v3
[*] use `on release` trigger for the `Release` workflow

[+] bump `elgohr/Publish-Docker-Github-Action` to v4, closes #469

---

.github/workflows/release.yml
docker-launcher-postgres.sh
docker/Dockerfile-daemon
docker/Dockerfile-db-bootstrapper
docker/Dockerfile-postgres
docker/Dockerfile-timescale
docker/Dockerfile-webui
postgresql_22.04.conf
supervisord-postgres.conf

[!] bump PostgreSQL to v15 in Docker images
[+] bump Grafana to v8.5.20 in Docker images
[+] bump Go to v1.20 in Docker images
closes #589

[!] bump PostgreSQL to v15, Grafana to v8.5.20, Go to v1.20 in Docker images

---

grafana_dashboards/postgres/v8/index-overview/dashboard.json

[-] fix dashboard typos

---

pgwatch2/metrics/db_stats/10/metric.sql
pgwatch2/metrics/db_stats/10/metric_su.sql
pgwatch2/metrics/db_stats/12/metric.sql
pgwatch2/metrics/db_stats/12/metric_su.sql
pgwatch2/metrics/db_stats/14/metric.sql
pgwatch2/metrics/db_stats/14/metric_su.sql
pgwatch2/metrics/db_stats/15/metric.sql
pgwatch2/metrics/db_stats/15/metric_su.sql
pgwatch2/metrics/invalid_indexes/10/metric.sql
pgwatch2/metrics/unused_indexes/10/metric.sql
pgwatch2/sql/config_store/metric_definitions.sql

Already covered by index_stats basically, but with a lot of other noise and a lot more row data

[+] add new metrics for invalid and unused indexes

---

docs/preparing_databases.rst

added GRANT EXECUTE ON FUNCTION pg_stat_file(text, boolean) to pgwatch2;

[*] update `preparing_databases.rst`
