- README.md
- pgwatch2/sql/datastore_setup/metric_definitions.sql
- pgwatch2/sql/metric_fetching_helpers/stat_activity_wrapper.sql
- pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql
Found an issue monitoring session information with the non-superuser role `pgwatch2`.
This PR adds a wrapper function to the database with privilege to execute only extended to `pgwatch2`, unless it is created by a superuser monitor login.
All existing metric queries have been updated to utilise the wrapper.
> Enable session monitoring by non-superuser role

- grafana_dashboards/stat-statements-top/dashboard.json
Avoids an influx error on grouping by time while not filtering by time
> Fix influx query for 'Stat statements top', 'Top queries by avg. runtime'

- pgwatch2/sql/metric_fetching_helpers/cpu_load_plpythonu_windows.sql
Python function for Windows that is used to extract CPU load from machine via SQL. Since os.getloadavg() function is unavailable for Windows, ctypes and kernel32.GetSystemTimes() along with TEMP TABLE used
> Functions for Windows servers to extract CPU load

- grafana_dashboards/v4/replication/dashboard.json
The Granafa v4 Replication dashboard needed some fix and improvements.
- Fixed the queries to compatible with new metric series;
- Added the follows items on the dashboard:
- Non-active replication stots(singlestat);
- Slot max restart_lsn lag(singlestat);
- Max. write lag(singlestat);
- Max. replay lag(singlestat);
- Replication slot restart_lsn lag(Graph);
- Replication write lag(Graph);
- Replication replay lag(Graph).
> Fixed and improved the dashboard v4 of Replication

- README.md
Hi there
I noted that commit 6db12e1755c843297f6aa982ce9dd2dcd96f7621 introduced new code which relies on Go's `math.round()`. This has only been added in Go 1.10, though the README.md for standalone installation still has 1.9.2 listed.
Even though it says "Install Go (latest version preferably)", I added the explicit remark that you absolutely need to have at least version 1.10 installed.
Just something minor, but nonetheless :)
Best regards
Lukas
> Added note for go requirements due to math.round() to README.md

- pgwatch2/sql/metric_store/01_old_metrics_cleanup_procedure.sql
- pgwatch2/sql/metric_store/metric-dbname-time/ensure_partition_metric_dbname_time.sql
To avoid too long partition name, use md5sum to shorten metric-dbname.
> Shorten partition name using md5sum

- README.md
Just a small documentation fix.
The table is actually called `metric`
> Fixed table name in README

- README.md
Add a badge to display the total amount of docker pulls to the README.
> Add badge to display docker pulls

- pgwatch2/metrics/00_helpers/get_load_average_copy/9.1/metric.sql
- pgwatch2/metrics/00_helpers/get_stat_statements/9.2/metric.sql
- pgwatch2/metrics/00_helpers/get_stat_statements/9.4/metric.sql
- pgwatch2/metrics/00_helpers/get_table_bloat_approx/9.5/metric.sql
- pgwatch2/metrics/00_helpers/get_table_bloat_approx_sql/12/metric.sql
- pgwatch2/metrics/00_helpers/get_table_bloat_approx_sql/9.0/metric.sql
- pgwatch2/sql/config_store/metric_definitions.sql
Fix "search_path" for those helpers that use some non-core views /
tables and error out when search_path has "public" CREATE privs
> More secure SECURITY DEFINER helpers

- pgwatch2/metrics/db_stats/14/metric.sql
- pgwatch2/metrics/db_stats/14/metric_su.sql
- pgwatch2/metrics/replication_slot_stats/14/metric.sql
- pgwatch2/metrics/wal_stats/14/metric.sql
- pgwatch2/sql/config_store/metric_definitions.sql
Some new views are more niche, so don't add the to default configs though
> Metrics: add new metrics for the upcoming Postgres v14 release.

- docker-launcher-postgres.sh
```
./build-docker-postgres.sh
docker run --rm -it -e PW2_TESTDB=true -P -p 8080:8080 -p 3000:3000 cybertec/pgwatch2-postgres
```
```
...
COMMENT
CREATE EXTENSION
ERROR:  relation "pg_qualstats_indexes_ddl" does not exist
INSERT 0 1
...
```
Current version of pg_qualstats extension (2.0.2) does not have pg_qualstats_indexes_ddl, it was removed at 2.0.0.
> Remove grant for removed table

- ENV_VARIABLES.md
- pgwatch2/logparse.go
- pgwatch2/pgwatch2.go
- pgwatch2/prom.go
A new --max-parallel-connections-per-db param to control max
simultaneous parallel queries to a monitered DB. NB! For dormant (not actively monitored DBs) the pool will be downscaled to max 1 concurrent connection if conn. pooling is enabled.
> Gatherer - full redesign of connection pooling, relying on *sqlx.DB

- pgwatch2/pgwatch2.go
Currently the startup can freeze for long periods on incorrect host info
or in case of real network problems / throttling
> Daemon: introduce a 5s connect timeout on opening Postgres connections

- docs/using_managed_services.rst
We've been asked by a customer how to monitor PostgreSQL instances created on
the Aiven platform with pgwatch2 and added some information about this to our
developer documentation.
The PR adds a link to said documentation, in case you're interested.
(Full disclosure: I work for Aiven)
> Docs: add Aiven as a cloud provider offering managed PostgreSQL

- pgwatch2/metrics/wal/10/metric.sql
- pgwatch2/metrics/wal/10/metric_su.sql
- pgwatch2/sql/config_store/metric_definitions.sql
Currently only detection of restarts is possible from metrics but for
failovers one needs to turn to logs
> Metrics: add "wal.timeline" column to be able to detect failovers

- pgwatch2/pgwatch2.go
Fix for 
```
WARN FetchMetricsPgpool: [pgpool_rolesdb][pgpool_stats] SHOW POOL_NODES needs to be placed before SHOW POOL_PROCESSES. ignoring SHOW POOL_PROCESSES
```
> [-] fix pgpool mode to execute only "non empty" queries 

- docs/docker_installation.rst
Path is /var/log/supervisor/ not /var/logs/supervisor/*
> Fix typo error

- grafana_dashboards/postgres/v8/index-overview/dashboard.json
- grafana_dashboards/postgres/v8/tables-top/dashboard.json
- pgwatch2/metrics/index-bloat/10/metric.sql
Since there is no panel in TablesTop that shows which table is bloated, it was added based on the existing table_bloat_approx_stattuple metric.
Following the same line and based on the experience of some cases where I have seen indexes bloats, a metric based on the pgstattuple extension with the help pgstatindex (leaf_fragmentation) function is proposed.
All this was tested in PostgreSQL 12.
> [+] add metric and dashboard for bloated indexes and tables

- pgwatch2/metrics/00_helpers/get_backup_age_pgbackrest/9.1/metric.sql
Cleanup code and fix issue where it could be left hanging when pgbackrest doesn't terminate in time, causing a long running transaction.
Note. Not tested yet.
> [*] сleanup pgbackrest helper function

- pgwatch2/pgwatch2.go
Fixed error "invalid command 'SET lock_timeout TO '100ms'" when connecting to pgbouncer DB type. https://github.com/cybertec-postgresql/pgwatch2/issues/507.
It is possible to add pgbouncer tables with the same structure as "show stats" to collect metrics from them. I was add 'show pools' table in tis commit
> [-] fix `Invalid command SET lock_timeout...` error, fixes #507

- pgwatch2/pgwatch2.go
reverts 0b3513576082480aada2a3765b5f4241a57fe83c
> [-] fix executing queries on standby databases with pooling, fixes #520

- grafana_dashboards/postgres/v8/stat-activity/dashboard.json
- grafana_dashboards/postgres/v8/stat-activity/title.txt
- pgwatch2/metrics/preset-configs.yaml
- pgwatch2/metrics/stat_activity/10/metric.sql
- pgwatch2/metrics/stat_activity/10/metric_su.sql
- pgwatch2/metrics/stat_statements/13/metric.sql
- pgwatch2/metrics/stat_statements/13/metric_su.sql
- pgwatch2/metrics/stat_statements/15/metric.sql
- pgwatch2/metrics/stat_statements/15/metric_su.sql
- pgwatch2/metrics/stat_statements/9.2/metric.sql
- pgwatch2/metrics/stat_statements/9.2/metric_su.sql
- pgwatch2/metrics/stat_statements/9.4/metric.sql
- pgwatch2/metrics/stat_statements/9.4/metric_su.sql
- pgwatch2/metrics/table_io_stats/10/metric.sql
- pgwatch2/metrics/table_stats/10/metric.sql
- pgwatch2/metrics/table_stats_approx/10/metric.sql
- pgwatch2/sql/config_store/config_store.sql
- pgwatch2/sql/config_store/metric_definitions.sql
Hello,
One of my collegue Manu G. has created a new report on stat-activity, to match our needs.
I have tested it, i think we should share.
Example
> [+] add new stat activity grid report

- pgwatch2/pgwatch2.go
Only one instance can now have the lock for
admin.all_distinct_dbname_metrics maintenance. Not 100% perfect though as connections interrupts can still lead to multiple updates per day but still much more resource-friendly than current state.
https://github.com/cybertec-postgresql/pgwatch2/issues/525
> [+] make unique dbname maintenance less costly for multi-daemon setups, fixes #525

- pgwatch2/metrics/wal/10/metric.sql
- pgwatch2/metrics/wal/10/metric_su.sql
- pgwatch2/sql/config_store/metric_definitions.sql
As timelineid is hexadecimal in pg_walfile_name(), this fix correctly convert it to int. 
Without this fix, queries fail when tlid reaches to A, and could give wrong results when decimals symbols is used
> [-] fix timeline ID conversion in `wal` metric from hexadecimal to decimal

- docker/launch-wrapper-db-bootstrapper.sh
As per the README[1], realtime statistics are stored in the metric-time schema format, even when other metrics are stored in timescaledb.
[1] https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/sql/metric_store/README.md#timescale
> [-] ensure bootstrap of a timescale metrics db includes necessary metric-time function

- pgwatch2/config/instances.yaml
Change cert_key to correct parameter.
Reopen #495
Minor change in instances example file for YAML based setup.
Configuration shows to require 'key_file' named parameter. 
https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L91
> [*] fix `key_file` to `key` on `host_config`

- docker-launcher-postgres.sh
- postgresql.conf
See on my 4 commit messages for description my fixes and optimizations for build docker image postgres and create/run as docker container.
Best regards,
Frank
> [-] fix `pgwatch2-postgres` Docker image

- pgwatch2/pgwatch2.go
If the gatherer is running with the '--conn-pooling on' option fetching pgbouncer metrics fails with errors "invalid command 'BEGIN READ WRITE'. Use SHOW HELP". This changes remove 'sqlLockTimeout' from 'sqlToExec' for pgbouncer metrics and assign usage 'DBExecRead' method for pgbouncer metrics independently of '--conn-pooling' option value
> [-] fix "invalid command 'BEGIN READ WRITE'" error when '--conn-pooling' option is on

- README.md
As of v1.10.0 pgwatch2 supports Postgres version 15. Readme should reflect it.
> [+] update README.md to show support of PG15

- README.md
- pgwatch2/metrics/index_stats/16/metric.sql
- pgwatch2/metrics/stat_io/16/metric.sql
- pgwatch2/metrics/stat_io/metric_attrs.yaml
- pgwatch2/metrics/table_stats/16/metric.sql
- pgwatch2/sql/config_store/metric_definitions.sql
Add most useful v16 introduced metrics awareness.
Add "last_scan" for index_stats / table_stats and a reduced version of pg_stat_io, grouped by backend type / total.
> [!] add metrics for PostgreSQL 16

- pgwatch2/metrics/00_helpers/rollout_helper.py
This is a fix for deprecated use of the yaml.load function. Apparently yaml.load carries some security concerns with how it de-serializes data from the yaml file, (arbitrary python code could be executed if embedded in the yaml file). As a result the library maintainers want users to be more explicit about what loader they are using to load the yaml.
The current usage of yaml.load in pgwatch2 is equivalent to the yaml.full_load function used in this PR. A safer choice might be the yaml.safe_load function but I would be concerned about regression issues.
Let me know if this change makes sense to you or if you want to drop down to using the safe_load function. Also let me know if you would like me to include some unit tests to prevent regressions/deprecation issues going forward.
> [-] fix warning about `yaml.load()` is deprecated, closes #738

- grafana_dashboards/postgres/v8/stat-activity/dashboard.json
Previous value was a numeric leading to import 
failure. This changes this value to null in order this 
dashboard to be importable
/closes #741
> [-] change `StatActivity` dashboard identifier value to `null`, closes #741

- helm-chart/templates/deployment.yaml
- webpy/templates/stats-summary.html
heya, 
hopefully uncontentious. 
i am running pgwatch as a helm chart, so different daemon and webui pods. 
previously there didn't seem to be any way to add additional env vars to the webui pod. 
obvs different ways to solve this problem, this seems easiest / best to me. 
not sure if sharing env vars between the daemon and webui pods is going to cause issues?
> [+] allow setting arbitrary configs to the webui pod

- pgwatch2/metrics/replication_slots/10/metric_master.sql
- pgwatch2/sql/config_store/metric_definitions.sql
This PR solve the following issue :
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
```
Since  `pg_current_wal_lsn()` execution is not allowed on replica instances `pg_last_wal_replay_lsn()` is used.
> [-] fix replication slots metrics for replica instances

- docker-launcher-scalefield.sh
- docker/Dockerfile-scalefield
- pgwatch2/config/scalefield.template
- alpine instead of ubuntu
- no need to cache metrics in combination with prometheus
> [*] optimize Scalefield image and enable async mode for prometheus
